export const AUTHENTICATED = 'Auth/AUTHENTICATED';
export const UNAUTHENTICATED = 'Auth/UNAUTHENTICATED';
export const AUTHENTICATION_ERROR = 'Auth/AUTHENTICATION_ERROR';
export const PAGE_LOADED = 'Auth/PAGE_LOADED';
